# Generated by Django 5.0.1 on 2024-01-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
