# Generated by Django 5.0.1 on 2024-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
